wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.12
    start_time: 1680676133
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.7.12
      5: 0.12.20
      8:
      - 1
      - 2
      - 5
_wandb_kernel:
  desc: null
  value: gpreda
dataset:
  desc: null
  value: elon-musk-tweets
project:
  desc: null
  value: EMTC
wandb:
  desc: null
  value: true
